package rtitools

import (
	"context"
	"encoding/json"
	"strings"
	"time"

	"github.com/rarity-ticket-intelligence/rarity/backend/internal/aiassist"
	"github.com/rarity-ticket-intelligence/rarity/backend/internal/authorization"
	"github.com/rarity-ticket-intelligence/rarity/backend/internal/clientresources"
	"github.com/rarity-ticket-intelligence/rarity/backend/internal/organizations"
	"github.com/rarity-ticket-intelligence/rarity/backend/internal/scope"
)

type ActiveClientResolver interface {
	ResolveActiveClient(
		context.Context,
		authorization.Principal,
		string,
		string,
	) (organizations.Client, error)
}

type ClientResourceCatalog interface {
	Query(context.Context, clientresources.QueryCommand) ([]clientresources.ResourceDetail, error)
	Resolve(context.Context, clientresources.ResolveCommand) (clientresources.ResourceDetail, error)
	Get(context.Context, clientresources.GetCommand) (clientresources.ResourceDetail, error)
	ResolveTrusted(context.Context, clientresources.TrustedResolveCommand) (clientresources.ResourceDetail, error)
	GetTrusted(context.Context, clientresources.TrustedGetCommand) (clientresources.ResourceDetail, error)
}

type LocationCreator interface {
	CreateLocation(context.Context, clientresources.CreateLocationCommand) (clientresources.Location, error)
}

type ContactCreator interface {
	CreateContact(context.Context, clientresources.CreateContactCommand) (clientresources.Contact, error)
}

type AssetCreator interface {
	CreateAsset(context.Context, clientresources.CreateAssetCommand) (clientresources.Asset, error)
}

type ServiceCreator interface {
	CreateService(context.Context, clientresources.CreateServiceCommand) (clientresources.ServiceRecord, error)
}

type ContractCreator interface {
	CreateContract(context.Context, clientresources.CreateContractCommand) (clientresources.Contract, error)
}

type clientResourceListRequest struct {
	Client string               `json:"client"`
	Kind   clientresources.Kind `json:"kind"`
	Query  *string              `json:"query,omitempty"`
	Limit  *int                 `json:"limit,omitempty"`
}

type clientResourceListInput struct {
	ClientID string               `json:"client_id"`
	Kind     clientresources.Kind `json:"kind"`
	Query    string               `json:"query,omitempty"`
	Limit    int                  `json:"limit"`
}

type locationCreateRequest struct {
	Client    string `json:"client"`
	DisplayID string `json:"display_id"`
	Name      string `json:"name"`
}

type contactCreateRequest struct {
	Client      string  `json:"client"`
	DisplayID   string  `json:"display_id"`
	DisplayName string  `json:"display_name"`
	Email       *string `json:"email,omitempty"`
	Phone       *string `json:"phone,omitempty"`
	Location    *string `json:"location,omitempty"`
}

type assetCreateRequest struct {
	Client       string  `json:"client"`
	DisplayID    string  `json:"display_id"`
	Name         string  `json:"name"`
	AssetType    string  `json:"asset_type"`
	Location     *string `json:"location,omitempty"`
	SourceSystem *string `json:"source_system,omitempty"`
	ExternalID   *string `json:"external_id,omitempty"`
}

type serviceCreateRequest struct {
	Client      string  `json:"client"`
	DisplayID   string  `json:"display_id"`
	Name        string  `json:"name"`
	Criticality *string `json:"criticality,omitempty"`
}

type contractCreateRequest struct {
	Client    string  `json:"client"`
	DisplayID string  `json:"display_id"`
	Name      string  `json:"name"`
	StartsOn  string  `json:"starts_on"`
	EndsOn    *string `json:"ends_on,omitempty"`
}

// resourceCreatePrepared has only identities generated by this adapter and
// values explicitly supplied by the user. It is never a public tool schema.
type resourceCreatePrepared struct {
	ClientID        string `json:"client_id"`
	ClientReference string `json:"client_reference"`
	ClientName      string `json:"client_name"`
	ClientDisplayID string `json:"client_display_id"`
	ResourceID      string `json:"resource_id"`
	DisplayID       string `json:"display_id"`
	Name            string `json:"name"`
	LocationID      string `json:"location_id,omitempty"`
	Email           string `json:"email,omitempty"`
	Phone           string `json:"phone,omitempty"`
	AssetType       string `json:"asset_type,omitempty"`
	SourceSystem    string `json:"source_system,omitempty"`
	ExternalID      string `json:"external_id,omitempty"`
	Criticality     string `json:"criticality,omitempty"`
	StartsOn        string `json:"starts_on,omitempty"`
	EndsOn          string `json:"ends_on,omitempty"`
}

func NewClientResourceListTool(
	directory ActiveClientResolver,
	catalog ClientResourceCatalog,
) aiassist.Tool {
	return &functionalTool{
		name: "client_resource.list", capability: "search.read", kind: aiassist.ToolRead,
		prepare: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (json.RawMessage, error) {
			request, err := decode[clientResourceListRequest](raw)
			if err != nil || directory == nil || catalog == nil || strings.TrimSpace(request.Client) == "" || !validResourceKind(request.Kind) {
				return nil, aiassist.ErrInvalidTool
			}
			limit := 25
			if request.Limit != nil {
				limit = *request.Limit
			}
			if limit < 1 || limit > 50 || !optionalValueValid(request.Query) {
				return nil, aiassist.ErrInvalidTool
			}
			client, err := resolveActiveResourceClient(ctx, directory, principal, "search.read", request.Client)
			if err != nil {
				return nil, err
			}
			return marshalPrepared(clientResourceListInput{ClientID: client.ID, Kind: request.Kind, Query: optionalValue(request.Query), Limit: limit})
		},
		validate: func(raw json.RawMessage) error {
			input, err := decode[clientResourceListInput](raw)
			if err != nil || strings.TrimSpace(input.ClientID) == "" || !validResourceKind(input.Kind) || input.Limit < 1 || input.Limit > 50 {
				return aiassist.ErrInvalidTool
			}
			return nil
		},
		resolve: resolveClientResourceScope,
		preview: noPreview,
		execute: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage, _ string) (aiassist.ToolResult, error) {
			input, err := decode[clientResourceListInput](raw)
			if err != nil || catalog == nil {
				return aiassist.ToolResult{}, aiassist.ErrInvalidTool
			}
			items, err := catalog.Query(ctx, clientresources.QueryCommand{
				Principal: principal, Target: target(principal, input.ClientID),
				Query: clientresources.Query{Kind: input.Kind, Literal: input.Query, Limit: input.Limit},
			})
			if err != nil {
				return aiassist.ToolResult{}, err
			}
			resources := make([]clientresources.Summary, 0, len(items))
			for _, item := range items {
				if item.LifecycleState != "active" {
					return aiassist.ToolResult{}, aiassist.ErrInvalidTool
				}
				resources = append(resources, item.Summary)
			}
			return aiassist.ToolResult{Summary: "Listed client resources", Data: map[string]any{"resources": resources}}, nil
		},
	}
}

func NewLocationCreateTool(directory ActiveClientResolver, creator LocationCreator, newID func() string) aiassist.Tool {
	return &functionalTool{
		name: "location.create", capability: "location.create", kind: aiassist.ToolWrite,
		prepare: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (json.RawMessage, error) {
			request, err := decode[locationCreateRequest](raw)
			if err != nil || creator == nil {
				return nil, aiassist.ErrInvalidTool
			}
			input, err := prepareResourceCreate(ctx, directory, principal, "location.create", request.Client, request.DisplayID, request.Name, newID)
			if err != nil {
				return nil, err
			}
			return marshalPrepared(input)
		},
		validate: validateLocationCreate,
		resolve:  resolveClientResourceScope,
		preview: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (aiassist.Preview, error) {
			input, err := validLocationCreate(raw)
			if err != nil {
				return aiassist.Preview{}, err
			}
			return createResourcePreview(ctx, directory, principal, "location.create", "location", input, baseResourceChanges(input))
		},
		execute: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage, correlationID string) (aiassist.ToolResult, error) {
			input, err := validLocationCreate(raw)
			if err != nil || creator == nil {
				return aiassist.ToolResult{}, aiassist.ErrInvalidTool
			}
			created, err := creator.CreateLocation(ctx, clientresources.CreateLocationCommand{
				Principal: principal, Target: target(principal, input.ClientID), DisplayID: input.DisplayID, Name: input.Name,
				ActorID: principal.ID, Source: "ai_workspace", Prepared: preparedIdentity(input, correlationID),
			})
			if err != nil {
				return aiassist.ToolResult{}, err
			}
			return resourceResult("location", created.ID, created.DisplayID, created.Name), nil
		},
	}
}

func NewContactCreateTool(directory ActiveClientResolver, catalog ClientResourceCatalog, creator ContactCreator, newID func() string) aiassist.Tool {
	return &functionalTool{
		name: "contact.create", capability: "contact.create", kind: aiassist.ToolWrite,
		prepare: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (json.RawMessage, error) {
			request, err := decode[contactCreateRequest](raw)
			if err != nil || creator == nil || !optionalValueValid(request.Email) || !optionalValueValid(request.Phone) || !optionalValueValid(request.Location) {
				return nil, aiassist.ErrInvalidTool
			}
			input, err := prepareResourceCreate(ctx, directory, principal, "contact.create", request.Client, request.DisplayID, request.DisplayName, newID)
			if err != nil {
				return nil, err
			}
			input.Email = optionalValue(request.Email)
			input.Phone = optionalValue(request.Phone)
			if input.LocationID, err = prepareLocationReference(ctx, catalog, principal, "contact.create", input.ClientID, request.Location); err != nil {
				return nil, err
			}
			return marshalPrepared(input)
		},
		validate: validateContactCreate,
		resolve:  resolveClientResourceScope,
		preview: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (aiassist.Preview, error) {
			input, err := validContactCreate(raw)
			if err != nil {
				return aiassist.Preview{}, err
			}
			changes := baseResourceChanges(input)
			var locationTarget *aiassist.PreviewTarget
			changes["display_name"] = aiassist.Change{Before: nil, After: input.Name}
			delete(changes, "name")
			if input.Email != "" {
				changes["email"] = aiassist.Change{Before: nil, After: input.Email}
			}
			if input.Phone != "" {
				changes["phone"] = aiassist.Change{Before: nil, After: input.Phone}
			}
			if input.LocationID != "" {
				location, err := currentActiveLocation(ctx, catalog, principal, "contact.create", input.ClientID, input.LocationID)
				if err != nil {
					return aiassist.Preview{}, err
				}
				changes["location"] = aiassist.Change{Before: nil, After: location.DisplayID}
				locationTarget = previewLocationTarget(input.ClientID, location)
			}
			preview, err := createResourcePreview(ctx, directory, principal, "contact.create", "contact", input, changes)
			if err != nil {
				return aiassist.Preview{}, err
			}
			preview.LocationTarget = locationTarget
			return preview, nil
		},
		execute: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage, correlationID string) (aiassist.ToolResult, error) {
			input, err := validContactCreate(raw)
			if err != nil || creator == nil {
				return aiassist.ToolResult{}, aiassist.ErrInvalidTool
			}
			created, err := creator.CreateContact(ctx, clientresources.CreateContactCommand{
				Principal: principal, Target: target(principal, input.ClientID), Location: resourceLocationRef(principal, input.ClientID, input.LocationID),
				DisplayID: input.DisplayID, DisplayName: input.Name, Email: input.Email, Phone: input.Phone, ActorID: principal.ID, Source: "ai_workspace", Prepared: preparedIdentity(input, correlationID),
			})
			if err != nil {
				return aiassist.ToolResult{}, err
			}
			return resourceResult("contact", created.ID, created.DisplayID, created.DisplayName), nil
		},
	}
}

func NewAssetCreateTool(directory ActiveClientResolver, catalog ClientResourceCatalog, creator AssetCreator, newID func() string) aiassist.Tool {
	return &functionalTool{
		name: "asset.create", capability: "asset.create", kind: aiassist.ToolWrite,
		prepare: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (json.RawMessage, error) {
			request, err := decode[assetCreateRequest](raw)
			if err != nil || creator == nil || !optionalValueValid(request.Location) || !optionalValueValid(request.SourceSystem) || !optionalValueValid(request.ExternalID) {
				return nil, aiassist.ErrInvalidTool
			}
			input, err := prepareResourceCreate(ctx, directory, principal, "asset.create", request.Client, request.DisplayID, request.Name, newID)
			if err != nil {
				return nil, err
			}
			input.AssetType, input.SourceSystem, input.ExternalID = strings.TrimSpace(request.AssetType), optionalValue(request.SourceSystem), optionalValue(request.ExternalID)
			if input.AssetType == "" {
				return nil, aiassist.ErrInvalidTool
			}
			if (input.SourceSystem == "") != (input.ExternalID == "") {
				return nil, aiassist.ErrInvalidTool
			}
			if input.LocationID, err = prepareLocationReference(ctx, catalog, principal, "asset.create", input.ClientID, request.Location); err != nil {
				return nil, err
			}
			return marshalPrepared(input)
		},
		validate: validateAssetCreate,
		resolve:  resolveClientResourceScope,
		preview: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (aiassist.Preview, error) {
			input, err := validAssetCreate(raw)
			if err != nil {
				return aiassist.Preview{}, err
			}
			changes := baseResourceChanges(input)
			var locationTarget *aiassist.PreviewTarget
			changes["asset_type"] = aiassist.Change{Before: nil, After: input.AssetType}
			changes["authority"] = aiassist.Change{Before: nil, After: clientresources.TechnicianConfirmed}
			if input.SourceSystem != "" {
				changes["source_system"] = aiassist.Change{Before: nil, After: input.SourceSystem}
			}
			if input.ExternalID != "" {
				changes["external_id"] = aiassist.Change{Before: nil, After: input.ExternalID}
			}
			if input.LocationID != "" {
				location, err := currentActiveLocation(ctx, catalog, principal, "asset.create", input.ClientID, input.LocationID)
				if err != nil {
					return aiassist.Preview{}, err
				}
				changes["location"] = aiassist.Change{Before: nil, After: location.DisplayID}
				locationTarget = previewLocationTarget(input.ClientID, location)
			}
			preview, err := createResourcePreview(ctx, directory, principal, "asset.create", "asset", input, changes)
			if err != nil {
				return aiassist.Preview{}, err
			}
			preview.LocationTarget = locationTarget
			return preview, nil
		},
		execute: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage, correlationID string) (aiassist.ToolResult, error) {
			input, err := validAssetCreate(raw)
			if err != nil || creator == nil {
				return aiassist.ToolResult{}, aiassist.ErrInvalidTool
			}
			created, err := creator.CreateAsset(ctx, clientresources.CreateAssetCommand{
				Principal: principal, Target: target(principal, input.ClientID), Location: resourceLocationRef(principal, input.ClientID, input.LocationID),
				DisplayID: input.DisplayID, Name: input.Name, AssetType: input.AssetType, SourceSystem: input.SourceSystem, ExternalID: input.ExternalID,
				Authority: clientresources.TechnicianConfirmed, ActorID: principal.ID, Source: "ai_workspace", Prepared: preparedIdentity(input, correlationID),
			})
			if err != nil {
				return aiassist.ToolResult{}, err
			}
			return resourceResult("asset", created.ID, created.DisplayID, created.Name), nil
		},
	}
}

func NewServiceCreateTool(directory ActiveClientResolver, creator ServiceCreator, newID func() string) aiassist.Tool {
	return &functionalTool{
		name: "service.create", capability: "service.create", kind: aiassist.ToolWrite,
		prepare: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (json.RawMessage, error) {
			request, err := decode[serviceCreateRequest](raw)
			if err != nil || creator == nil || !optionalValueValid(request.Criticality) {
				return nil, aiassist.ErrInvalidTool
			}
			input, err := prepareResourceCreate(ctx, directory, principal, "service.create", request.Client, request.DisplayID, request.Name, newID)
			if err != nil {
				return nil, err
			}
			input.Criticality = optionalValue(request.Criticality)
			if input.Criticality != "" && !validCriticality(input.Criticality) {
				return nil, aiassist.ErrInvalidTool
			}
			return marshalPrepared(input)
		},
		validate: validateServiceCreate,
		resolve:  resolveClientResourceScope,
		preview: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (aiassist.Preview, error) {
			input, err := validServiceCreate(raw)
			if err != nil {
				return aiassist.Preview{}, err
			}
			changes := baseResourceChanges(input)
			if input.Criticality != "" {
				changes["criticality"] = aiassist.Change{Before: nil, After: input.Criticality}
			}
			return createResourcePreview(ctx, directory, principal, "service.create", "service", input, changes)
		},
		execute: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage, correlationID string) (aiassist.ToolResult, error) {
			input, err := validServiceCreate(raw)
			if err != nil || creator == nil {
				return aiassist.ToolResult{}, aiassist.ErrInvalidTool
			}
			created, err := creator.CreateService(ctx, clientresources.CreateServiceCommand{
				Principal: principal, Target: target(principal, input.ClientID), DisplayID: input.DisplayID, Name: input.Name, Criticality: input.Criticality,
				ActorID: principal.ID, Source: "ai_workspace", Prepared: preparedIdentity(input, correlationID),
			})
			if err != nil {
				return aiassist.ToolResult{}, err
			}
			return resourceResult("service", created.ID, created.DisplayID, created.Name), nil
		},
	}
}

func NewContractCreateTool(directory ActiveClientResolver, creator ContractCreator, newID func() string) aiassist.Tool {
	return &functionalTool{
		name: "contract.create", capability: "contract.create", kind: aiassist.ToolWrite,
		prepare: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (json.RawMessage, error) {
			request, err := decode[contractCreateRequest](raw)
			if err != nil || creator == nil || !optionalValueValid(request.EndsOn) || !validDate(request.StartsOn) || (request.EndsOn != nil && !validDate(*request.EndsOn)) {
				return nil, aiassist.ErrInvalidTool
			}
			if request.EndsOn != nil && !dateNotBefore(*request.EndsOn, request.StartsOn) {
				return nil, aiassist.ErrInvalidTool
			}
			input, err := prepareResourceCreate(ctx, directory, principal, "contract.create", request.Client, request.DisplayID, request.Name, newID)
			if err != nil {
				return nil, err
			}
			input.StartsOn, input.EndsOn = strings.TrimSpace(request.StartsOn), optionalValue(request.EndsOn)
			return marshalPrepared(input)
		},
		validate: validateContractCreate,
		resolve:  resolveClientResourceScope,
		preview: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage) (aiassist.Preview, error) {
			input, err := validContractCreate(raw)
			if err != nil {
				return aiassist.Preview{}, err
			}
			changes := baseResourceChanges(input)
			changes["starts_on"] = aiassist.Change{Before: nil, After: input.StartsOn}
			if input.EndsOn != "" {
				changes["ends_on"] = aiassist.Change{Before: nil, After: input.EndsOn}
			}
			return createResourcePreview(ctx, directory, principal, "contract.create", "contract", input, changes)
		},
		execute: func(ctx context.Context, principal authorization.Principal, raw json.RawMessage, correlationID string) (aiassist.ToolResult, error) {
			input, err := validContractCreate(raw)
			if err != nil || creator == nil {
				return aiassist.ToolResult{}, aiassist.ErrInvalidTool
			}
			startsOn, _ := parseDate(input.StartsOn)
			var endsOn *time.Time
			if input.EndsOn != "" {
				value, _ := parseDate(input.EndsOn)
				endsOn = &value
			}
			created, err := creator.CreateContract(ctx, clientresources.CreateContractCommand{
				Principal: principal, Target: target(principal, input.ClientID), DisplayID: input.DisplayID, Name: input.Name, StartsOn: startsOn, EndsOn: endsOn,
				ActorID: principal.ID, Source: "ai_workspace", Prepared: preparedIdentity(input, correlationID),
			})
			if err != nil {
				return aiassist.ToolResult{}, err
			}
			return resourceResult("contract", created.ID, created.DisplayID, created.Name), nil
		},
	}
}

func resolveActiveResourceClient(ctx context.Context, directory ActiveClientResolver, principal authorization.Principal, capability, reference string) (organizations.Client, error) {
	if directory == nil || strings.TrimSpace(principal.Scope.MSPID) == "" {
		return organizations.Client{}, aiassist.ErrInvalidTool
	}
	return directory.ResolveActiveClient(ctx, principal, capability, strings.TrimSpace(reference))
}

func prepareResourceCreate(ctx context.Context, directory ActiveClientResolver, principal authorization.Principal, capability, clientReference, displayID, name string, newID func() string) (resourceCreatePrepared, error) {
	if newID == nil || strings.TrimSpace(displayID) == "" || strings.TrimSpace(name) == "" {
		return resourceCreatePrepared{}, aiassist.ErrInvalidTool
	}
	client, err := resolveActiveResourceClient(ctx, directory, principal, capability, clientReference)
	if err != nil {
		return resourceCreatePrepared{}, err
	}
	resourceID := strings.TrimSpace(newID())
	if resourceID == "" {
		return resourceCreatePrepared{}, aiassist.ErrInvalidTool
	}
	return resourceCreatePrepared{ClientID: client.ID, ClientReference: strings.TrimSpace(clientReference), ClientName: client.Name, ClientDisplayID: client.DisplayID, ResourceID: resourceID, DisplayID: strings.TrimSpace(displayID), Name: strings.TrimSpace(name)}, nil
}

func prepareLocationReference(ctx context.Context, catalog ClientResourceCatalog, principal authorization.Principal, capability, clientID string, reference *string) (string, error) {
	if reference == nil {
		return "", nil
	}
	if catalog == nil || strings.TrimSpace(*reference) == "" {
		return "", aiassist.ErrInvalidTool
	}
	location, err := catalog.ResolveTrusted(ctx, clientresources.TrustedResolveCommand{
		Principal: principal, Target: target(principal, clientID), Kind: clientresources.LocationKind,
		Reference: strings.TrimSpace(*reference), Capability: capability,
	})
	if err != nil {
		return "", err
	}
	if !isActiveLocation(location) {
		return "", clientresources.ErrLifecycleConflict
	}
	return location.ID, nil
}

func currentActiveLocation(ctx context.Context, catalog ClientResourceCatalog, principal authorization.Principal, capability, clientID, locationID string) (clientresources.ResourceDetail, error) {
	if catalog == nil {
		return clientresources.ResourceDetail{}, aiassist.ErrInvalidTool
	}
	location, err := catalog.GetTrusted(ctx, clientresources.TrustedGetCommand{
		Principal: principal, Target: target(principal, clientID), Kind: clientresources.LocationKind,
		ID: locationID, Capability: capability,
	})
	if err != nil {
		return clientresources.ResourceDetail{}, err
	}
	if !isActiveLocation(location) {
		return clientresources.ResourceDetail{}, clientresources.ErrLifecycleConflict
	}
	return location, nil
}

func isActiveLocation(location clientresources.ResourceDetail) bool {
	return strings.TrimSpace(location.ID) != "" && location.Kind == string(clientresources.LocationKind) && location.LifecycleState == "active"
}

func resolveClientResourceScope(principal authorization.Principal, raw json.RawMessage) (scope.Target, error) {
	return resolveScoped(principal, raw)
}

func marshalPrepared(value any) (json.RawMessage, error) {
	prepared, err := json.Marshal(value)
	if err != nil {
		return nil, aiassist.ErrInvalidTool
	}
	return prepared, nil
}

func validateLocationCreate(raw json.RawMessage) error {
	_, err := validLocationCreate(raw)
	return err
}
func validateContactCreate(raw json.RawMessage) error { _, err := validContactCreate(raw); return err }
func validateAssetCreate(raw json.RawMessage) error   { _, err := validAssetCreate(raw); return err }
func validateServiceCreate(raw json.RawMessage) error { _, err := validServiceCreate(raw); return err }
func validateContractCreate(raw json.RawMessage) error {
	_, err := validContractCreate(raw)
	return err
}

func validLocationCreate(raw json.RawMessage) (resourceCreatePrepared, error) {
	return validResourceCreate(raw, func(input resourceCreatePrepared) bool {
		return input.LocationID == "" && input.Email == "" && input.Phone == "" && input.AssetType == "" &&
			input.SourceSystem == "" && input.ExternalID == "" && input.Criticality == "" &&
			input.StartsOn == "" && input.EndsOn == ""
	})
}
func validContactCreate(raw json.RawMessage) (resourceCreatePrepared, error) {
	return validResourceCreate(raw, func(input resourceCreatePrepared) bool {
		return input.AssetType == "" && input.SourceSystem == "" && input.ExternalID == "" &&
			input.Criticality == "" && input.StartsOn == "" && input.EndsOn == ""
	})
}
func validAssetCreate(raw json.RawMessage) (resourceCreatePrepared, error) {
	return validResourceCreate(raw, func(input resourceCreatePrepared) bool {
		return input.AssetType != "" && input.Email == "" && input.Phone == "" && input.Criticality == "" &&
			(input.SourceSystem == "") == (input.ExternalID == "") &&
			input.StartsOn == "" && input.EndsOn == ""
	})
}
func validServiceCreate(raw json.RawMessage) (resourceCreatePrepared, error) {
	return validResourceCreate(raw, func(input resourceCreatePrepared) bool {
		return input.LocationID == "" && input.Email == "" && input.Phone == "" && input.AssetType == "" &&
			input.SourceSystem == "" && input.ExternalID == "" && input.StartsOn == "" && input.EndsOn == "" &&
			(input.Criticality == "" || validCriticality(input.Criticality))
	})
}
func validContractCreate(raw json.RawMessage) (resourceCreatePrepared, error) {
	return validResourceCreate(raw, func(input resourceCreatePrepared) bool {
		return input.LocationID == "" && input.Email == "" && input.Phone == "" && input.AssetType == "" &&
			input.SourceSystem == "" && input.ExternalID == "" && input.Criticality == "" &&
			validDate(input.StartsOn) && (input.EndsOn == "" || (validDate(input.EndsOn) && dateNotBefore(input.EndsOn, input.StartsOn)))
	})
}

func validResourceCreate(raw json.RawMessage, additional func(resourceCreatePrepared) bool) (resourceCreatePrepared, error) {
	input, err := decode[resourceCreatePrepared](raw)
	if err != nil || strings.TrimSpace(input.ClientID) == "" || strings.TrimSpace(input.ClientReference) == "" || strings.TrimSpace(input.ClientName) == "" || strings.TrimSpace(input.ClientDisplayID) == "" || strings.TrimSpace(input.ResourceID) == "" || strings.TrimSpace(input.DisplayID) == "" || strings.TrimSpace(input.Name) == "" || !additional(input) {
		return resourceCreatePrepared{}, aiassist.ErrInvalidTool
	}
	return input, nil
}

func baseResourceChanges(input resourceCreatePrepared) map[string]aiassist.Change {
	return map[string]aiassist.Change{"display_id": {Before: nil, After: input.DisplayID}, "name": {Before: nil, After: input.Name}, "lifecycle_state": {Before: nil, After: "active"}}
}

func createResourcePreview(ctx context.Context, directory ActiveClientResolver, principal authorization.Principal, capability, kind string, input resourceCreatePrepared, changes map[string]aiassist.Change) (aiassist.Preview, error) {
	client, err := resolveActiveResourceClient(ctx, directory, principal, capability, input.ClientReference)
	if err != nil {
		return aiassist.Preview{}, err
	}
	if client.ID != input.ClientID {
		return aiassist.Preview{}, aiassist.ErrProposalStale
	}
	changes["client"] = aiassist.Change{Before: nil, After: map[string]string{"display_id": client.DisplayID, "name": client.Name}}
	return aiassist.Preview{Summary: "Create " + kind + " " + input.Name, TargetType: kind, TargetID: input.ResourceID, TargetVersion: 0, Changes: changes}, nil
}

func previewLocationTarget(clientID string, location clientresources.ResourceDetail) *aiassist.PreviewTarget {
	return &aiassist.PreviewTarget{
		ID:        location.ID,
		ClientID:  clientID,
		Kind:      string(clientresources.LocationKind),
		DisplayID: location.DisplayID,
		Name:      location.Name,
	}
}

func preparedIdentity(input resourceCreatePrepared, correlationID string) clientresources.PreparedIdentity {
	return clientresources.PreparedIdentity{ResourceID: input.ResourceID, CorrelationID: correlationID}
}

func resourceLocationRef(principal authorization.Principal, clientID, locationID string) clientresources.Ref {
	if locationID == "" {
		return clientresources.Ref{}
	}
	return clientresources.Ref{ID: locationID, MSPID: principal.Scope.MSPID, ClientID: clientID}
}

func resourceResult(kind, id, displayID, name string) aiassist.ToolResult {
	return aiassist.ToolResult{Summary: "Created " + displayID, Data: map[string]any{"resource_type": kind, "resource_id": id, "display_id": displayID, "name": name}}
}

func optionalValue(value *string) string {
	if value == nil {
		return ""
	}
	return strings.TrimSpace(*value)
}
func optionalValueValid(value *string) bool { return value == nil || strings.TrimSpace(*value) != "" }
func validDate(value string) bool {
	_, err := parseDate(value)
	return strings.TrimSpace(value) != "" && err == nil
}
func parseDate(value string) (time.Time, error) {
	return time.Parse("2006-01-02", strings.TrimSpace(value))
}
func dateNotBefore(end, start string) bool {
	endDate, endErr := parseDate(end)
	startDate, startErr := parseDate(start)
	return endErr == nil && startErr == nil && !endDate.Before(startDate)
}

func validResourceKind(kind clientresources.Kind) bool {
	switch kind {
	case clientresources.LocationKind, clientresources.ContactKind, clientresources.AssetKind, clientresources.ServiceKind, clientresources.ContractKind:
		return true
	default:
		return false
	}
}

func validCriticality(value string) bool {
	switch strings.TrimSpace(value) {
	case "low", "normal", "high", "critical":
		return true
	default:
		return false
	}
}
