import type {
  ConversionPreviewModel,
  ProjectWorkspace,
} from "./features/projects/types";
import type {
  OpportunityWorkspace,
  ProposalWorkspace,
} from "./features/sales/types";

export const opportunity: OpportunityWorkspace = {
  id: "OPP-1042",
  name: "Northwind security modernization",
  clientName: "Northwind Legal",
  ownerName: "Priya Shah",
  teamName: "Advisory",
  stage: { id: "discovery", name: "Discovery", probability: 40, ageDays: 12 },
  nextStage: {
    id: "proposal",
    name: "Proposal",
    probability: 65,
    ageDays: 0,
    requiresProposal: true,
  },
  expectedValueMinor: 4800000,
  currency: "USD",
  expectedCloseOn: "Aug 28, 2026",
  version: 7,
  activities: [
    { id: "a1", at: "Today, 9:42 AM", text: "Discovery call completed." },
    {
      id: "a2",
      at: "Yesterday",
      text: "Security scope and licensing quantities reviewed.",
    },
  ],
  tasks: [
    { id: "task-1", title: "Schedule kickoff", completed: false },
    { id: "task-2", title: "Qualify prospect", completed: true },
  ],
  proposalVersions: [
    {
      id: "pv2",
      version: 2,
      state: "accepted",
      totalMinor: 4800000,
      marginMinor: 1600000,
      currency: "USD",
      issuedAt: "Jul 28, 2026",
      acceptance: {
        method: "electronic",
        signerName: "Jordan Lee",
        acceptedAt: "Jul 29, 2026",
      },
    },
    {
      id: "pv1",
      version: 1,
      state: "issued",
      totalMinor: 4500000,
      marginMinor: 1400000,
      currency: "USD",
      issuedAt: "Jul 22, 2026",
      acceptance: null,
    },
  ],
};

export const proposal: ProposalWorkspace = {
  id: "PROP-81",
  currency: "USD",
  approvalState: "approved",
  versions: opportunity.proposalVersions,
  lines: [
    {
      id: "line-1",
      type: "fixed_fee",
      description: "Discovery and architecture",
      quantity: 1,
      unitPriceMinor: 1200000,
      unitCostMinor: 400000,
      discountMinor: 0,
      plannedMinutes: 1200,
    },
    {
      id: "line-2",
      type: "time_and_materials",
      description: "Endpoint hardening deployment",
      quantity: 1,
      unitPriceMinor: 3600000,
      unitCostMinor: 2000000,
      discountMinor: 0,
      plannedMinutes: 6000,
    },
  ],
};

export const conversionPreview: ConversionPreviewModel = {
  hash: "approved-preview-hash",
  opportunityID: opportunity.id,
  proposalVersionID: "pv2",
  client: {
    action: "match",
    clientID: "northwind",
    name: "Northwind Legal",
  },
  projectDisplayID: "PRJ-204",
  projectName: "Security modernization",
  currency: "USD",
  originalBudgetMinor: 4800000,
  plannedMinutes: 7200,
  phases: [
    {
      position: 1,
      name: "Discovery",
      proposalLineIDs: ["line-1"],
      plannedMinutes: 1200,
      budgetMinor: 1200000,
    },
    {
      position: 2,
      name: "Delivery",
      proposalLineIDs: ["line-2"],
      plannedMinutes: 6000,
      budgetMinor: 3600000,
    },
  ],
  tasks: [
    { id: "task-1", title: "Schedule kickoff", version: 2, completed: false },
    { id: "task-2", title: "Qualify prospect", version: 4, completed: true },
  ],
};

export const project: ProjectWorkspace = {
  id: "project-id",
  displayID: "PRJ-204",
  name: "Security modernization",
  clientName: "Northwind Legal",
  lifecycleState: "Planned",
  plannedStart: "Aug 3, 2026",
  plannedEnd: "Aug 28, 2026",
  originalProposalVersion: 2,
  phases: [
    {
      id: "phase-1",
      position: 1,
      name: "Discovery",
      state: "Complete",
      ownerName: "Priya Shah",
      participatingTeams: ["Advisory"],
      plannedMinutes: 1200,
      actualMinutes: 1080,
      deliverables: ["Approved architecture"],
      completionCriteria: ["Client sign-off"],
      tasks: [
        {
          id: "task-1",
          title: "Schedule kickoff",
          ownerName: "Alex Morgan",
          completed: true,
          subtasks: 2,
          plannedMinutes: 240,
          actualMinutes: 180,
        },
      ],
    },
    {
      id: "phase-2",
      position: 2,
      name: "Delivery",
      state: "In progress",
      ownerName: "Marcus Reed",
      participatingTeams: ["Security", "Service Desk"],
      plannedMinutes: 6000,
      actualMinutes: 1560,
      deliverables: ["Hardened endpoint baseline"],
      completionCriteria: ["Validation report accepted"],
      tasks: [
        {
          id: "task-3",
          title: "Deploy endpoint hardening baseline",
          ownerName: "Marcus Reed",
          completed: false,
          subtasks: 4,
          plannedMinutes: 480,
          actualMinutes: 120,
        },
      ],
    },
  ],
  capacity: [
    {
      id: "tech-1",
      name: "Marcus Reed",
      role: "Security Engineer",
      availableMinutes: 2400,
      scheduledMinutes: 2880,
      actualMinutes: 720,
      overbookedMinutes: 1200,
    },
    {
      id: "team-1",
      name: "Service Desk",
      role: "Participating team",
      availableMinutes: 4800,
      scheduledMinutes: 1800,
      actualMinutes: 600,
      overbookedMinutes: 0,
    },
  ],
  financials: {
    currency: "USD",
    originalBudgetMinor: 4800000,
    currentBudgetMinor: 4800000,
    plannedLaborMinor: 2400000,
    actualLaborMinor: 960000,
    actualLaborComplete: true,
    costActualsMinor: 420000,
    committedCostMinor: 260000,
    billableWorkMinor: 2200000,
    profitMinor: 820000,
    profitAvailable: true,
    projectedProfitMinor: 1720000,
    marginBasisPoints: 3727,
  },
  changeOrders: [
    {
      id: "co-12",
      displayID: "CO-12",
      state: "issued",
      version: 3,
      currentVersion: {
        id: "cov-2",
        version: 2,
        description: "Add endpoint hardening",
        currency: "USD",
        revenueDeltaMinor: 240000,
        costDeltaMinor: 80000,
        laborDeltaMinutes: 720,
      },
      decisions: [],
    },
  ],
};
